#!/bin/bash
aws ec2 describe-instances --filters "Name=tag:Role,Values=BigIqLicenseManager" --query 'Reservations[*].Instances[*].NetworkInterfaces[*].PrivateIpAddresses[*].Association.PublicIp' --output text

