#!/bin/bash
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i MyKeyPair-$emailid.pem admin@$1 show sys mcp-state field-fmt |grep -qE 'phase.+running'
if [ $? ]; then
 echo 'resetting password'
 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i MyKeyPair-$emailid.pem admin@$1 modify /auth user admin password $shortUrl
 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i MyKeyPair-$emailid.pem admin@$1 save /sys config
 else
 echo 'not running, try again'
fi

