#!/bin/bash
INSTALL_DIR=/usr/local

function terraform-install() {
  [[ -f ${INSTALL_DIR}/bin/terraform ]] && echo "`${INSTALL_DIR}/bin/terraform version` already installed at ${INSTALL_DIR}/bin/terraform" && return 0
  LATEST_URL=$(curl -sL https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].builds[].url' | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | egrep -v 'rc|beta' | egrep 'linux.*amd64' |tail -1)
  curl ${LATEST_URL} > /tmp/terraform.zip
  mkdir -p ${INSTALL_DIR}/bin
  (cd ${INSTALL_DIR}/bin && unzip /tmp/terraform.zip)
  if [[ -z $(grep 'export PATH=${INSTALL_DIR}/bin:${PATH}' ~/.bashrc) ]]; then
  	echo 'export PATH=${INSTALL_DIR}/bin:${PATH}' >> ~/.bashrc
  fi
  
  echo "Installed: `${INSTALL_DIR}/bin/terraform version`"
  
  cat - << EOF 
 
Run the following to reload your PATH with terraform:

  source ~/.bashrc

EOF
}

terraform-install
